# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#group_imports
group_imports = "StdExternalCrate"
# https://rust-lang.github.io/rustfmt/?version=v1.4.36&search=#imports_granularity
imports_granularity = "Module"
max_width = 120
